common/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'common'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.common, name=app_name),

    path('venues/', views.VenuesListView.as_view(), name="venues"),
    path('venues/<slug:slug>-<int:pk>/', views.VenueDetailView.as_view(), name="venue-details"),

    path('search/', views.search_results, name="search-results"),
]

products/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'products'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.products, name=app_name),

    path('events/', views.EventsListView.as_view(), name="events"),
    path('events/<slug:slug>-<int:pk>/', views.EventDetailView.as_view(), name="event-details"),

    path('create-event/', views.create_event, name="create-event"),
    path('update-event/<slug:slug>-<int:pk>/', views.UpdateEventView.as_view(), name="update-event"),
    path('delete-event/<slug:slug>-<int:pk>/', views.DeleteEventView.as_view(), name="delete-event"),

    path('create-ticket/<slug:event_slug>-<int:event_pk>/', views.create_ticket, name="create-ticket"),
    path('update-ticket/<slug:event_slug>-<int:event_pk>/<slug:ticket_slug>-<int:ticket_pk>/', views.UpdateTicketView.as_view(), name="update-ticket"),
    path('delete-ticket/<slug:event_slug>-<int:event_pk>/<slug:ticket_slug>-<int:ticket_pk>/', views.DeleteTicketView.as_view(), name="delete-ticket"),

    path('statistics/<slug:slug>-<int:pk>/', views.event_statistics, name="event-statistics"),
]

tickez/urls.py
from django.contrib import admin

from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
from django.views.generic.base import RedirectView


# definizione degli URL patterns per l'applicazione + aggiunta URL per servire file statici e media in fase di sviluppo
urlpatterns = [
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico', permanent=True)),
    re_path(r"^$|^\/$|^home\/$", views.home_page, name='homepage'),

    path('common/', include('common.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),

    re_path(r"^404/$", views.custom_404_view, name="404"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# personalizzazione dei titoli dell'area di amministrazione
admin.site.site_header = "Tickez Administration Page"
admin.site.site_title = "Tickez"
admin.site.index_title = "Admin Area"

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.users, name=app_name),

    path('register/', views.CustomerCreateView.as_view(), name='register-customer'),
    path('register-organizer/', views.OrganizerCreateView.as_view(), name='register-organizer'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('admin-profile/', views.AdminProfileView.as_view(), name="admin-profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),

    path('toggle-follow/<str:entity_type>/<int:entity_pk>/', views.toggle_follow, name='toggle-follow'),

    path('artists/', views.ArtistsListView.as_view(), name="artists"),
    path('artists/<slug:slug>-<int:pk>/', views.ArtistDetailView.as_view(), name="artist-details"),
]

common/models.py
from django.db import models

from django.conf import settings

from os.path import join
from django.urls import reverse

from django.template.defaultfilters import slugify

from django.utils import timezone


class Luogo(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    slug = models.SlugField(max_length=200, null=False, blank=True, unique=True)
    indirizzo = models.CharField(max_length=255, null=False, blank=False)
    citta = models.CharField(max_length=100, null=False, blank=False)
    capienza_persone = models.PositiveIntegerField(null=False, blank=False)
    immagine = models.ImageField(null=True, blank=True, upload_to="images/venues")

    followers = models.ManyToManyField(to='users.Utente', blank=True, default=None, related_name='luoghi_preferiti')
    affittuari = models.ManyToManyField(to='users.Organizzatore', blank=True, default=None, related_name='luoghi_affittati')
    

    def __str__(self):
        return f"{self.nome} - {self.indirizzo}, {self.citta}"
    
    # django tratta il valore di default di un ImageField come un file media, cercandolo nella directory MEDIA_ROOT
    @property # trasforma un metodo di una classe in un attributo di sola lettura
    def immagine_url(self):
        if self.immagine and hasattr(self.immagine, 'url'):
            return self.immagine.url
        else:
            return join(settings.STATIC_URL, 'images/defaults/default_venue.jpg')

    # restituisce l'URL assoluto per la visualizzazione dettagliata di un Luogo
    def get_absolute_url(self):
        return reverse("common:venue-details", kwargs={"slug": self.slug, "pk": self.pk})
    
    # lo slug viene aggiornato alla creazione di un Luogo e ad ogni modifica del suo nome
    def save(self, *args, **kwargs):
        if not self.slug or slugify(self.nome) != self.slug:
            self.slug = slugify(self.nome)
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Luoghi'


class Notifica(models.Model):
    testo = models.CharField(max_length=50, null=False, blank=False)
    data_ora = models.DateTimeField(null=False, blank=False, default=timezone.now)
    letta = models.BooleanField(default=False)

    ordine = models.ForeignKey(to='orders.Ordine', on_delete=models.CASCADE, null=True, blank=True, related_name='notifiche_ordine')
    evento = models.ForeignKey(to='products.Evento', on_delete=models.CASCADE, null=True, blank=True, related_name='notifiche_evento')
    organizzatore = models.ForeignKey(to='users.Organizzatore', on_delete=models.CASCADE, null=True, blank=True, related_name='notifiche_organizzatore')
    luogo = models.ForeignKey(Luogo, on_delete=models.CASCADE, null=True, blank=True, related_name='notifiche_luogo')
    

    def __str__(self):
        return f"{self.testo}"

    class Meta:
        verbose_name_plural = 'Notifiche'

common/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404

from django.views.generic import ListView, DetailView

from common.models import Luogo
from products.models import Evento
from users.models import Organizzatore

from django.core.paginator import Paginator

from products.filters import EventoFilter


def common(request):
    return render(request, '404.html', status=404)

# elenco luoghi, in ordine alfabetico
class VenuesListView(ListView):
    model = Luogo
    template_name = 'common/venues.html' 
    paginate_by = 8

    def get_queryset(self):
        venue_list = super().get_queryset()
        
        return venue_list.order_by('nome')
    
# dettagli luogo
class VenueDetailView(DetailView):
    model = Luogo
    template_name = "common/venue_details.html"
    paginate_by = 4

    def dispatch(self, request, *args, **kwargs):
        # gestisce eventuali eccezioni Http404 che potrebbero essere sollevate durante il processo di elaborazione della richiesta
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return render(request, '404.html', status=404)

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        pk = self.kwargs.get('pk')
        return get_object_or_404(Luogo, slug=slug, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = self.get_object().nome

        events = self.get_object().eventi_programmati.order_by('data_ora')
        paginator = Paginator(events, self.paginate_by)
        # con get_page django gestisce internamente le eccezioni e garantisce che venga sempre restituita una pagina valida.
        events = paginator.get_page(self.request.GET.get('page'))

        context['planned_events'] = events

        return context
    
# funzionalità di ricerca tramite 'keywords'
def search_results(request):
    events = Evento.objects.all()
    venues = Luogo.objects.all()
    artists = Organizzatore.objects.all()
    keywords = request.GET.get('keywords', '').strip()
    
    if keywords:
        search_terms = keywords.split()

        for term in search_terms:
            events = events.filter(nome__icontains=term)
            artists = artists.filter(nome__icontains=term)
            venues = venues.filter(nome__icontains=term)

    # applicazione del form di filtraggio agli eventi
    evento_filter = EventoFilter(request.GET, queryset=events)
    events = evento_filter.qs

    total_events = events.count()
    total_artists = artists.count()
    total_venues = venues.count()
    
    # paginazione dei risultati
    events_paginator = Paginator(events, 5)
    artists_paginator = Paginator(artists.order_by('nome'), 8)
    venues_paginator = Paginator(venues.order_by('nome'), 8)
    # con get_page django gestisce internamente le eccezioni e garantisce che venga sempre restituita una pagina valida.
    events = events_paginator.get_page(request.GET.get('page_events'))
    artists = artists_paginator.get_page(request.GET.get('page_artists'))
    venues = venues_paginator.get_page(request.GET.get('page_venues'))

    return render(request, 'common/search_results.html', {
        'events': events, 
        'venues': venues, 
        'artists': artists, 
        'keywords': keywords,
        'total_events': total_events,
        'total_artists': total_artists,
        'total_venues': total_venues,
        'filter': evento_filter,
    })

common/templates/common/base_common.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

common/templates/common/home_page.html
{% extends "common/base_common.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}Tickez | Biglietti per Concerti, Festival e Teatro{% endblock %}

{% block content %}
<!-- link diretti alla visualizzazione degli eventi filtrati per catgoria (Concerti, Festival e Teatro) -->
<div class="container">
    <h4 style="font-weight: bold; margin-top: 20px;">Categorie</h4>
    <hr style="opacity:0.1;">
    <div class="row">
        <div class="col-md-4 col-sm-4 d-flex justify-content-center">
            <a href="{% url 'products:events' %}?category=Concerti" class="w-100 text-decoration-none">
            <div class="card bg-dark text-white w-100" style="height: 12rem">
                <img src="{% static 'images/thumbnails/concerti.jpg' %}" class="card-img" alt="Concerti">
                <div class="card-img-overlay d-flex justify-content-center align-items-center">
                    <h3 class="card-title">Concerti</h3>
                </div>
            </div>
            </a>
        </div>
        <div class="col-md-4 col-sm-4 d-flex justify-content-center">
            <a href="{% url 'products:events' %}?category=Festival" class="w-100 text-decoration-none">
            <div class="card bg-dark text-white w-100" style="height: 12rem">
                <img src="{% static 'images/thumbnails/festival.jpg' %}" class="card-img" alt="Festival">
                <div class="card-img-overlay d-flex justify-content-center align-items-center">
                    <h3 class="card-title">Festival</h3>
                </div>
            </div>
            </a>
        </div>
        <div class="col-md-4 col-sm-4 d-flex justify-content-center">
            <a href="{% url 'products:events' %}?category=Teatro" class="w-100 text-decoration-none">
            <div class="card bg-dark text-white w-100" style="height: 12rem">
                <img src="{% static 'images/thumbnails/teatro.jpg' %}" class="card-img" alt="Teatro">
                <div class="card-img-overlay d-flex justify-content-center align-items-center">
                    <h3 class="card-title">Teatro</h3>
                </div>
            </div>
            </a>
        </div>
    </div>
</div>
<div style="height: 70px;"></div>
<!-- la sezione degli eventi consigliati viene visualizzata solo da utenti autenticati che hanno effettuato almeno un acquisto -->
{% if recommended_events %}
<div class="container">
    <h4 style="font-weight: bold;">Consigliati per te</h4>
    <hr style="opacity:0.1;">
    <div class="scroll-container">
        <ul class="horizontal-list">
            {% for e in recommended_events %}
                <li class="card" style="width: 20rem;">
                    <!-- la property locandina_url viene utilizzata, appunto, per recuperare l'url dell'immagine -->
                    <img src="{{ e.locandina_url }}" class="card-img-top w-100" style="height: 166px; object-fit: cover;">
                    <div class="card-body d-flex flex-column justify-content-center">
                        <p class="card-title" style="font-weight:600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{e.nome}}</p>
                        <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{e.organizzatore}}<br>{{e.luogo.nome}}<br>{{e.data_ora|date:"d/m/Y"}}</p>
                        <p></p>
                        <a href="{{ e.get_absolute_url }}" class="btn btn-dark btn-sm mt-auto">Dettagli</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div style="height: 35px;"></div>
{% endif %}
<!-- visualizzazione "parziale" degli eventi in ordine di data crescente -->
<div class="container">
    <h4 style="font-weight: bold;">Prossimi eventi</h4>
    <hr style="opacity:0.1;">
    {% if object_list %}
    <div class="scroll-container">
        <ul class="horizontal-list">
            {% for e in object_list %}
                <li class="card" style="width: 20rem;">
                    <!-- la property locandina_url viene utilizzata, appunto, per recuperare l'url dell'immagine -->
                    <img src="{{ e.locandina_url }}" class="card-img-top w-100" style="height: 166px; object-fit: cover;">
                    <div class="card-body d-flex flex-column justify-content-center">
                        <p class="card-title" style="font-weight:600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{e.nome}}</p>
                        <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{e.organizzatore}}<br>{{e.luogo.nome}}<br>{{e.data_ora|date:"d/m/Y"}}</p>
                        <p></p>
                        <a href="{{ e.get_absolute_url }}" class="btn btn-dark btn-sm mt-auto">Dettagli</a>
                    </div>
                </li>
            {% endfor %}
            <li class="button d-flex justify-content-center align-items-center" style="width: 14rem;">
                <a href="{% url 'products:events' %}" class="btn btn-dark btn-lg">Vedi tutti</a>
            </li>
        </ul>
    </div>
    {% else %}
        <p>Nessun evento disponibile</p>
    {% endif %}
</div>
<div style="height: 70px;"></div>
<!-- link diretti alla visualizzazione degli Artisti, organizzatori degli eventi, e i Luoghi che li possono ospitare -->
<div class="container">
    <h4 style="font-weight: bold;">Scopri</h4>
    <hr style="opacity:0.1;">
    <div class="row">
        <div class="col-md-6 col-sm-6 d-flex">
            <a href="{% url 'users:artists' %}" class="w-100 text-decoration-none">
            <div class="card bg-dark text-white w-100" style="height: 12rem">
                <img src="{% static 'images/thumbnails/artisti.jpg' %}" class="card-img" alt="Festival">
                <div class="card-img-overlay d-flex justify-content-center align-items-center">
                    <h3 class="card-title">Artisti</h3>
                </div>
            </div>
            </a>
        </div>
        <div class="col-md-6 col-sm-6 d-flex">
            <a href="{% url 'common:venues' %}" class="w-100 text-decoration-none">
            <div class="card bg-dark text-white w-100" style="height: 12rem">
                <img src="{% static 'images/thumbnails/luoghi.jpg' %}" class="card-img" alt="Festival">
                <div class="card-img-overlay d-flex justify-content-center align-items-center">
                    <h3 class="card-title">Luoghi</h3>
                </div>
            </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}

common/templates/common/venue_details.html
{% extends "common/base_common.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}{{title}} | Tickez{% endblock %}

{% block content %}
<div class="container">
  <div class="d-flex align-items-center mb-5">
    <div class="me-3" style="width: 300px; height: 200px;">
        <img src="{{ object.immagine_url }}" style="width: 100%; height: 100%; object-fit: cover; border: 5px solid black;">
    </div>

    <div style="flex-grow: 1; max-width: calc(100% - 220px);">
        <h1 class="mb-3" style="font-weight:600; word-break: break-word;">{{ object.nome }}</h1>

        <p><strong>Informazioni:</strong><br>- {{object.indirizzo}}, {{object.citta}}<br>- Capienza: {{object.capienza_persone}} persone</p>

        {% if request.user.utente or request.user.is_superuser or not request.user.is_authenticated %}
        <form method="POST" action="{% url 'users:toggle-follow' entity_type='luogo' entity_pk=object.id %}"> {% csrf_token %}
            <input type="hidden" name="action" value="{% if request.user.utente in object.followers.all %}unfollow{% else %}follow{% endif %}">
            
            <button type="submit" class="btn {% if request.user.utente in object.followers.all %}btn-secondary{% else %}btn-dark{% endif %} mt-2">
                {% if request.user.utente in object.followers.all %}
                    <i class="fas fa-heart me-1"></i> Seguito
                {% else %}
                    <i class="far fa-heart me-1"></i> Segui
                {% endif %}
            </button>
        </form>
        {% endif %}
    </div>
  </div>


  <div>
      <h3 class="mb-3">Eventi programmati:</h3>
      {% if planned_events %}
      {% for e in planned_events %}
      <div class="card mb-3">
          <div class="row g-0">
              <div class="col-4" style="max-width: 256px;">
                  <img src="{{ e.locandina_url }}" class="img-fluid rounded-start" alt="{{ e.nome }}" style="width: 256px; height:166px; object-fit: cover;">
              </div>
              <div class="col-7">
                  <div class="card-body">
                      <h5 class="card-title mt-1 mb-2" style="font-weight:600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{ e.nome }}</h5>
                      <p></p>
                      <p class="card-text">{{ e.luogo.nome }}<br>{{e.luogo.indirizzo}}, {{e.luogo.citta}}</p>
                      <p class="card-text">{{e.data_ora|date:"d/m/Y, l"|slice:":15"}} {{e.data_ora|time:"H:i"}}</p>
                  </div>
              </div>
              <div class="card-body col-1 d-flex align-items-center justify-content-end">
                      <a href="{{ e.get_absolute_url }}" class="btn btn-dark">Biglietti <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
              </div>
          </div>
      </div>
      {% endfor %}
      <!-- paginazione -->
      <nav aria-label="Page navigation">
          <ul class="pagination pagination-sm justify-content-center">
              <li class="page-item">
                  {% if planned_events.has_previous %}
                      <a class="page-link" href="?page={{ planned_events.previous_page_number }}" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                      </a>
                  {% endif %}
              </li>

              <!-- link di paginazione per pagina corrente e adiacenti -->
              {% for num in planned_events.paginator.page_range %}
                  {% if planned_events.number == num %}
                      <li class="page-item active" aria-current="page">
                          <span class="page-link">{{ num }}</span>
                      </li>
                  {% elif num > planned_events.number|add:'-2' and num < planned_events.number|add:'2' %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                      </li>
                  {% endif %}
              {% endfor %}

              <li class="page-item">
                  {% if planned_events.has_next %}
                      <a class="page-link" href="?page={{ planned_events.next_page_number }}" aria-label="Next">
                          <span aria-hidden="true">&raquo;</span>
                      </a>
                  {% endif %}
              </li>
          </ul>
      </nav>
      {% else %}
          <p>Nessun evento programmato.</p>
      {% endif %}
  </div>
</div>
{% endblock %}

common/templates/common/venues.html
{% extends "common/base_common.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Luoghi | Tickez{% endblock %}

{% block content %}
<div class="container">
    <h1>Luoghi</h1>
    <h5 class="mt-3 mb-5">Risultati: {{view.get_queryset.count}}</h5>

    <div class="row row-cols-1 row-cols-4 g-3">
        {% for v in page_obj %}
        <div class="col">
            <div class="card" style="height:275px;">
                <img src="{{ v.immagine_url }}" class="card-img-top h-100" alt="{{ v.nome }}" style="max-height:225px; object-fit: cover; object-position: center;">
                <div class="card-body d-flex flex-column">
                    <p class="card-title" style="font-weight:600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{ v.nome }}</p>
                    <p></p>
                    <a href="{{ v.get_absolute_url }}" class="btn btn-dark btn-sm mt-auto">Dettagli</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- paginazione -->
    <nav class="mt-3" aria-label="Page navigation">
        <ul class="pagination pagination-sm justify-content-center">
            <li class="page-item">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            {% endif %}
            </li>

            <!-- link di paginazione per pagina corrente e adiacenti -->
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item">
            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
            </li>
        </ul>
    </nav>

</div>
{% endblock %}