tickez/urls.py
from django.contrib import admin

from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
from django.views.generic.base import RedirectView


# definizione degli URL patterns per l'applicazione + aggiunta URL per servire file statici e media in fase di sviluppo
urlpatterns = [
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico', permanent=True)),
    re_path(r"^$|^\/$|^home\/$", views.home_page, name='homepage'),

    path('common/', include('common.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),

    re_path(r"^404/$", views.custom_404_view, name="404"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# personalizzazione dei titoli dell'area di amministrazione
admin.site.site_header = "Tickez Administration Page"
admin.site.site_title = "Tickez"
admin.site.index_title = "Admin Area"

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.users, name=app_name),

    path('register/', views.CustomerCreateView.as_view(), name='register-customer'),
    path('register-organizer/', views.OrganizerCreateView.as_view(), name='register-organizer'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('admin-profile/', views.AdminProfileView.as_view(), name="admin-profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),

    path('toggle-follow/<str:entity_type>/<int:entity_pk>/', views.toggle_follow, name='toggle-follow'),

    path('artists/', views.ArtistsListView.as_view(), name="artists"),
    path('artists/<slug:slug>-<int:pk>/', views.ArtistDetailView.as_view(), name="artist-details"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

from django.template.defaultfilters import slugify

from django.utils import timezone

from django.conf import settings
from os.path import join


class Utente(models.Model):
    GENDER_CHOICES = [('Altro', 'Altro'), ('Maschio', 'Maschio'), ('Femmina', 'Femmina')]

    nome = models.CharField(max_length=50, null=False, blank=False)
    cognome = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=255, null=False, blank=False, unique=True)
    data_nascita = models.DateField(null=False, blank=False, default=timezone.now)
    sesso = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True, default='Altro')
    stato = models.CharField(max_length=50, null=True, blank=True)
    telefono = models.CharField(max_length=20, null=True, blank=True, default=None)
    immagine_profilo = models.ImageField(null=True, blank=True, upload_to="images/customers")

    '''
    l'eliminazione non è bidirezionale per impostazione predefinita per motivi di sicurezza e integrità dei dati.
    l'oggetto User, quindi, persiste anche se l'oggetto Utente viene eliminato
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.nome} {self.cognome} - {self.user.username}"
    
    # sincronizzazione tra i campi nome, cognome ed email delle tabelle users_utente e auth_user
    def save(self, *args, **kwargs):
        self.user.first_name = self.nome
        self.user.last_name = self.cognome
        self.user.email = self.email
        self.user.save()
        super(Utente, self).save(*args, **kwargs)
    
    # django tratta il valore di default di un ImageField come un file media, cercandolo nella directory MEDIA_ROOT
    @property # trasforma un metodo di una classe in un attributo di sola lettura
    def immagine_profilo_url(self):
        if self.immagine_profilo and hasattr(self.immagine_profilo, 'url'):
            return self.immagine_profilo.url
        else:
            return join(settings.STATIC_URL, 'images/defaults/default_user.jpg')

    class Meta:
        verbose_name_plural = 'Utenti'


class Organizzatore(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    slug = models.SlugField(max_length=100, null=False, blank=True, unique=True)
    email = models.EmailField(max_length=255, null=False, blank=False, unique=True)
    descrizione = models.TextField(null=True, blank=True, default='')
    immagine_profilo = models.ImageField(null=True, blank=True, upload_to="images/organizers")

    '''
    l'eliminazione non è bidirezionale per impostazione predefinita per motivi di sicurezza e integrità dei dati.
    l'oggetto User, quindi, persiste anche se l'oggetto Organizzatore viene eliminato
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField(Utente, blank=True, default=None, related_name='organizzatori_preferiti')


    def __str__(self):
        return self.nome
    
    # restituisce l'URL assoluto per la visualizzazione dettagliata di un Organizzatore
    def get_absolute_url(self):
        return reverse("users:artist-details", kwargs={"slug": self.slug, "pk": self.pk})
    
    def save(self, *args, **kwargs):
        # sincronizzazione dell'email tra users_utente e auth_user
        self.user.email = self.email
        self.user.save()
        
        # lo slug viene aggiornato alla creazione di un Organizzatore e ad ogni modifica del suo nome
        if not self.slug or slugify(self.nome) != self.slug:
            self.slug = slugify(self.nome)
        super().save(*args, **kwargs)

    # django tratta il valore di default di un ImageField come un file media, cercandolo nella directory MEDIA_ROOT
    @property # trasforma un metodo di una classe in un attributo di sola lettura
    def immagine_profilo_url(self):
        if self.immagine_profilo and hasattr(self.immagine_profilo, 'url'):
            return self.immagine_profilo.url
        else:
            return join(settings.STATIC_URL, 'images/defaults/default_user.jpg')

    class Meta:
        verbose_name_plural = 'Organizzatori'

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.urls import reverse_lazy

from django.contrib import messages
from urllib.parse import urlparse

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from braces.views import SuperuserRequiredMixin

from django.views.generic import ListView, DetailView, CreateView, UpdateView

from django.contrib.auth.models import User
from users.models import Organizzatore
from common.models import Luogo
from products.models import Evento

from django.core.paginator import Paginator

from .forms import *


def users(request):
    return render(request, '404.html', status=404)


# login
def login_user(request):
    if request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST["password"]
        # verifica se l'utente esiste nel sistema e se le credenziali fornite sono corrette
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next')
            if next_url:
                # verifica che il next_url sia un URL sicuro (relativo)
                parsed_next_url = urlparse(next_url)
                if parsed_next_url.path.startswith('/'):
                    return redirect(next_url)
            messages.success(request, 'Accesso effettuato con successo. Bentornato su Tickez!')
            return redirect('homepage')
        else:
            messages.error(request, ("Si è verificato un errore. Riprova"))
            return redirect('users:login')
    else:
        return render(request, 'users/registration/login.html', {})
    

# creazione Utente
class CustomerCreateView(CreateView):
    form_class = CustomerCreationForm
    template_name = "users/registration/user_create.html"
    success_url = reverse_lazy("homepage")

    # aggiunge logica eseguita prima di ogni richiesta
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, "Effettua il logout per poter registrare un nuovo profilo.")
            return redirect("homepage")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, "Registrazione avvenuta con successo. Benvenuto su Tickez!")
        return redirect(self.success_url)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Utente'
        return context
    

# creazione Organizzatore
class OrganizerCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "is_staff" # solo l'admin (is_staff di default) può registrare gli organizzatori
    form_class = OrganizerCreationForm
    template_name = "users/registration/user_create.html"
    success_url = reverse_lazy("homepage")

    def form_valid(self, form):
        user = form.save()
        login(self.request, self.request.user)
        messages.success(self.request, "Account Organizzatore creato con successo!")
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Organizzatore'
        return context
    

# funzione di test per gestire l'autenticazione degli utenti
def is_customer(user):
    return user.groups.filter(name="Clienti").exists()

@user_passes_test(is_customer)
# funzionalità follow-unfollow
def toggle_follow(request, entity_type, entity_pk):
    # mappa il tipo di entità al modello corrispondente
    entity_model = {
        'evento': Evento,
        'organizzatore': Organizzatore,
        'luogo': Luogo,
    }
    try:
        entity = get_object_or_404(entity_model[entity_type], pk=entity_pk)

        if request.method == "POST":
            if request.POST.get('action') == 'follow':
                if request.user.utente not in entity.followers.all():
                    entity.followers.add(request.user.utente)
                    return redirect(entity.get_absolute_url())
            elif request.POST.get('action') == 'unfollow':
                if request.user.utente in entity.followers.all():
                    entity.followers.remove(request.user.utente)
                    return redirect(entity.get_absolute_url())
                
        return redirect(entity.get_absolute_url())
    except KeyError:
        return render(request, '404.html', status=404)
    except Http404:
        return render(request, '404.html', status=404)


# visualizzazione profilo admin
class AdminProfileView(SuperuserRequiredMixin, DetailView):
    model = User
    template_name = 'users/admin_profile.html'
    success_url = reverse_lazy('users:admin-profile')

    def get_object(self, queryset=None):
        return self.request.user
    

# visualizzazione profilo Utente o Organizzatore
class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    orders_per_page = 5 # ordini
    events_per_page = 4 # eventi
    starred_per_page = 8 # artisti e luoghi

    def dispatch(self, request, *args, **kwargs):
        # gestisce eventuali eccezioni Http404 che potrebbero essere sollevate durante il processo di elaborazione della richiesta
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return render(request, '404.html', status=404)

    def get_object(self, queryset=None):
        if hasattr(self.request.user, 'organizzatore'):
            return get_object_or_404(Organizzatore, user=self.request.user)
        else:
            return get_object_or_404(Utente, user=self.request.user)

    def get_form_class(self):
        if hasattr(self.request.user, 'organizzatore'):
            return OrganizzatoreEditCrispyForm
        else:
            return CustomerEditCrispyForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_owner = self.get_object()

        context['is_organizer'] = hasattr(self.request.user, 'organizzatore')
        context['user'] = self.request.user
        context['immagine_profilo'] = profile_owner.immagine_profilo_url

        orders_paginator = Paginator(profile_owner.ordini.order_by('-data_ora'), self.orders_per_page)
        # con get_page django gestisce internamente le eccezioni e garantisce che venga sempre restituita una pagina valida.
        context['orders'] = orders_paginator.get_page(self.request.GET.get('page_orders'))

        if hasattr(self.request.user, 'organizzatore'):
            events_paginator = Paginator(profile_owner.eventi_organizzati.order_by('data_ora'), self.starred_per_page)
            context['events'] = events_paginator.get_page(self.request.GET.get('page_events'))
        else:
            starred_events_paginator = Paginator(profile_owner.eventi_preferiti.order_by('data_ora'), self.events_per_page)
            context['starred_events'] = starred_events_paginator.get_page(self.request.GET.get('page_starred_events'))

            starred_artists_paginator = Paginator(profile_owner.organizzatori_preferiti.order_by('nome'), self.starred_per_page)
            context['starred_artists'] = starred_artists_paginator.get_page(self.request.GET.get('page_starred_artists'))

            starred_locations_paginator = Paginator(profile_owner.luoghi_preferiti.order_by('nome'), self.starred_per_page)
            context['starred_locations'] = starred_locations_paginator.get_page(self.request.GET.get('page_starred_locations'))
       
        return context
    

# elenco artisti (organizzatori), in ordine alfabetico
class ArtistsListView(ListView):
    model = Organizzatore
    template_name = 'users/artists.html' 
    paginate_by = 8

    def get_queryset(self):
        artist_list = super().get_queryset()
        
        return artist_list.order_by('nome')
    

# dettagli artista (organizzatore)
class ArtistDetailView(DetailView):
    model = Organizzatore
    template_name = "users/artist_details.html"
    paginate_by = 4

    def dispatch(self, request, *args, **kwargs):
        # gestisce eventuali eccezioni Http404 che potrebbero essere sollevate durante il processo di elaborazione della richiesta
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return render(request, '404.html', status=404)

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        pk = self.kwargs.get('pk')
        return get_object_or_404(Organizzatore, slug=slug, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = self.object.nome

        events = self.object.eventi_organizzati.order_by('data_ora')
        paginator = Paginator(events, self.paginate_by)
        # con get_page django gestisce internamente le eccezioni e garantisce che venga sempre restituita una pagina valida.
        events = paginator.get_page(self.request.GET.get('page'))
        
        context['planned_events'] = events

        return context

users/templates/users/admin_profile.html
{% extends "users/base_users.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Admin Area | Tickez{% endblock %}

{% block content %}
{% if user.is_superuser %}
    <div class="container">
        <h1 class="mb-5">Admin Area</h1>

        <div class="d-flex justify-content-center mb-5">
            <a href="{% url 'admin:index' %}" class="btn btn-success">Accedi al Portale di Amministrazione</a>
        </div>
        <div class="d-flex justify-content-center mb-3">
            <a href="{% url 'users:register-organizer' %}" class="btn btn-dark">Registra Organizzatore</a>
        </div>
    </div>
{% endif %}
{% endblock %}

users/templates/users/artist_details.html
{% extends "users/base_users.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}{{title}} | Tickez{% endblock %}

{% block content %}
<div class="container">
  <div class="d-flex align-items-center mb-5">
    <div class="me-3" style="width: 300px; height: 200px;">
        <img src="{{ object.immagine_profilo_url }}" style="width: 100%; height: 100%; object-fit: cover; border: 5px solid black;">
    </div>

    <div style="flex-grow: 1; max-width: calc(100% - 220px);">
        <h1 class="mb-3" style="font-weight:600; word-break: break-word;">{{ object.nome }}</h1>

        {% if request.user.utente or request.user.is_superuser or not request.user.is_authenticated %}
        <form method="POST" action="{% url 'users:toggle-follow' entity_type='organizzatore' entity_pk=object.id %}"> {% csrf_token %}
            <input type="hidden" name="action" value="{% if request.user.utente in object.followers.all %}unfollow{% else %}follow{% endif %}">
            <button type="submit" class="btn {% if request.user.utente in object.followers.all %}btn-secondary{% else %}btn-dark{% endif %} mt-2">
                {% if request.user.utente in object.followers.all %}
                    <i class="fas fa-heart me-1"></i> Seguito
                {% else %}
                    <i class="far fa-heart me-1"></i> Segui
                {% endif %}
            </button>
        </form>
        {% endif %}
    </div>
  </div>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="events-tab" data-bs-toggle="tab" data-bs-target="#events" type="button" role="tab" aria-controls="events" aria-selected="false">Eventi organizzati</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" aria-selected="true">Descrizione</button>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane mt-3 active" id="events" role="tabpanel" aria-labelledby="events-tab">
        {% if planned_events %}
        {% for e in planned_events %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-4" style="max-width: 256px;">
                    <img src="{{ e.locandina_url }}" class="img-fluid rounded-start" alt="{{ e.nome }}" style="width: 256px; height:166px; object-fit: cover;">
                </div>
                <div class="col-7">
                    <div class="card-body">
                        <h5 class="card-title mt-1 mb-2" style="font-weight:600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{ e.nome }}</h5>
                        <p></p>
                        <p class="card-text">{{ e.luogo.nome }}<br>{{e.luogo.indirizzo}}, {{e.luogo.citta}}</p>
                        <p class="card-text">{{e.data_ora|date:"d/m/Y, l"|slice:":15"}} {{e.data_ora|time:"H:i"}}</p>
                    </div>
                </div>
                <div class="card-body col-1 d-flex align-items-center justify-content-end">
                        <a href="{{ e.get_absolute_url }}" class="btn btn-dark">Biglietti <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- paginazione -->
        <nav aria-label="Page navigation">
            <ul class="pagination pagination-sm justify-content-center">
                <li class="page-item">
                    {% if planned_events.has_previous %}
                        <a class="page-link" href="?page={{ planned_events.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% endif %}
                </li>

                <!-- link di paginazione per pagina corrente e adiacenti -->
                {% for num in planned_events.paginator.page_range %}
                    {% if planned_events.number == num %}
                        <li class="page-item active" aria-current="page">
                            <span class="page-link">{{ num }}</span>
                        </li>
                    {% elif num > planned_events.number|add:'-2' and num < planned_events.number|add:'2' %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item">
                    {% if planned_events.has_next %}
                        <a class="page-link" href="?page={{ planned_events.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>
        {% else %}
            <p>Nessun evento organizzato.</p>
        {% endif %}
      </div>
      <div class="tab-pane mt-3" id="description" role="tabpanel" aria-labelledby="description-tab">{{object.descrizione}}</div>
    </div>
</div>
{% endblock %}

users/templates/users/artists.html
{% extends "users/base_users.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Artisti | Tickez{% endblock %}

{% block content %}
<div class="container">
    <h1>Artisti</h1>
    <h5 class="mt-3 mb-5">Risultati: {{view.get_queryset.count}}</h5>

    <div class="row row-cols-1 row-cols-4 g-3">
        {% for a in page_obj %}
        <div class="col">
            <div class="card" style="height:275px;">
                <img src="{{ a.immagine_profilo_url }}" class="card-img-top h-100" alt="{{ a.nome }}" style="max-height:225px; object-fit: cover; object-position: center;">
                <div class="card-body d-flex flex-column">
                    <p class="card-title" style="font-weight:600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{ a.nome }}</p>
                    <p></p>
                    <a href="{{ a.get_absolute_url }}" class="btn btn-dark btn-sm mt-auto">Dettagli</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- paginazione -->
    <nav class="mt-3" aria-label="Page navigation">
        <ul class="pagination pagination-sm justify-content-center">
            <li class="page-item">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            {% endif %}
            </li>

            <!-- link di paginazione per pagina corrente e adiacenti -->
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item">
            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

users/templates/users/base_users.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}