common/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'common'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.common, name=app_name),

    path('venues/', views.VenuesListView.as_view(), name="venues"),
    path('venues/<slug:slug>-<int:pk>/', views.VenueDetailView.as_view(), name="venue-details"),

    path('search/', views.search_results, name="search-results"),
]

products/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'products'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.products, name=app_name),

    path('events/', views.EventsListView.as_view(), name="events"),
    path('events/<slug:slug>-<int:pk>/', views.EventDetailView.as_view(), name="event-details"),

    path('create-event/', views.create_event, name="create-event"),
    path('update-event/<slug:slug>-<int:pk>/', views.UpdateEventView.as_view(), name="update-event"),
    path('delete-event/<slug:slug>-<int:pk>/', views.DeleteEventView.as_view(), name="delete-event"),

    path('create-ticket/<slug:event_slug>-<int:event_pk>/', views.create_ticket, name="create-ticket"),
    path('update-ticket/<slug:event_slug>-<int:event_pk>/<slug:ticket_slug>-<int:ticket_pk>/', views.UpdateTicketView.as_view(), name="update-ticket"),
    path('delete-ticket/<slug:event_slug>-<int:event_pk>/<slug:ticket_slug>-<int:ticket_pk>/', views.DeleteTicketView.as_view(), name="delete-ticket"),

    path('statistics/<slug:slug>-<int:pk>/', views.event_statistics, name="event-statistics"),
]

tickez/urls.py
from django.contrib import admin

from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
from django.views.generic.base import RedirectView


# definizione degli URL patterns per l'applicazione + aggiunta URL per servire file statici e media in fase di sviluppo
urlpatterns = [
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico', permanent=True)),
    re_path(r"^$|^\/$|^home\/$", views.home_page, name='homepage'),

    path('common/', include('common.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),

    re_path(r"^404/$", views.custom_404_view, name="404"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# personalizzazione dei titoli dell'area di amministrazione
admin.site.site_header = "Tickez Administration Page"
admin.site.site_title = "Tickez"
admin.site.index_title = "Admin Area"

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.users, name=app_name),

    path('register/', views.CustomerCreateView.as_view(), name='register-customer'),
    path('register-organizer/', views.OrganizerCreateView.as_view(), name='register-organizer'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('admin-profile/', views.AdminProfileView.as_view(), name="admin-profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),

    path('toggle-follow/<str:entity_type>/<int:entity_pk>/', views.toggle_follow, name='toggle-follow'),

    path('artists/', views.ArtistsListView.as_view(), name="artists"),
    path('artists/<slug:slug>-<int:pk>/', views.ArtistDetailView.as_view(), name="artist-details"),
]

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link rel="shortcut icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

    <!-- datepicker form di filtraggio -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bootstrap.datepicker-fork/1.3.0/js/locales/bootstrap-datepicker.it.js"></script> 
    <script src="{% static 'js/datepicker.js' %}"></script>
    
    <!-- statistiche -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
    <script>
      // funzione utilizzata per rimuovere parametri GET inutili (from_date e until_date vuoti), ad ogni caricamento di una pagina
      function cleanURL() {
        var url = window.location.href;
        var cleanUrl = url.replace(/[^?=&]+=(&|$)/g, "").replace(/&$/, "");
        window.history.replaceState({}, document.title, cleanUrl);
      }
      window.onload = function() {
          cleanURL();
      };
    </script>
    

    {% block head %} {% endblock %}

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <br/>
    <div class="container">
    {% if messages %}
      {% for m in messages %}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.293 10.707a1 1 0 0 0 1.414 0l4-4a1 1 0 1 0-1.414-1.414L7 8.586 5.707 7.293a1 1 0 0 0-1.414 1.414l2 2z"/>
            </symbol>
            <symbol id="info-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 1.5a6.5 6.5 0 1 0 6.5 6.5A6.508 6.508 0 0 0 8 1.5zm0 11a1.5 1.5 0 1 1 1.5-1.5A1.5 1.5 0 0 1 8 12.5zm.866-3.32a.5.5 0 1 1-.732.68A2.502 2.502 0 0 1 8 10a2.5 2.5 0 1 1 .866-3.82.5.5 0 0 1 .732.68A1.5 1.5 0 0 0 8 9a1.5 1.5 0 0 0 .866-.32z"/>
            </symbol>
        </svg>
        
        {% if m.tags == 'success' %}
        <div class="alert alert-{{ m.tags }} alert-dismissible fade show d-flex align-items-center" role="alert" style="font-size: 0.9rem; border-radius: 0.25rem;">
          <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        {% elif m.tags == 'info' or m.tags == 'debug' %}
        <div class="alert alert-{{ m.tags }} alert-dismissible fade show d-flex align-items-center" role="alert" style="font-size: 0.9rem; border-radius: 0.25rem;">
          <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Info:"><use xlink:href="#info-circle-fill"/></svg>
        {% elif m.tags == 'warning' %}
        <div class="alert alert-{{ m.tags }} alert-dismissible fade show d-flex align-items-center" role="alert" style="font-size: 0.9rem; border-radius: 0.25rem;">
          <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        {% else %}
        <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert" style="font-size: 0.9rem; border-radius: 0.25rem;">
          <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        {% endif %}
          {{ m }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
    </div>

    {% block content %} {% endblock %}

    <br/><br/>
    {% include 'footer.html' %}
  </body>
</html>

templates/footer.html
<footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <a href="/"><img width="150" heigth="150" src="/static/images/tickez_logo.jpg"/></a>
        </div>
        <div class="col-md-3 col-xs-12">
          <h6>Tickez</h6>
          <ul class="footer-links">
            <li><p>Chi siamo</p></li>
            <li><p>Stampa</p></li>
            <li><p>Lavora con noi</p></li>
          </ul>
        </div>
        <div class="col-md-3 col-xs-12">
          <h6>Assistenza Clienti</h6>
          <ul class="footer-links">
            <li><p>Termini e condizioni d'acquisto</p></li>
            <li><p>Contattaci</p></li>
            <li><p>FAQ</p></li>
          </ul>
        </div>
      </div>
      <hr>
    </div>
    
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <p class="copyright-text">&copy; 2024 Tickez.&ensp;All Rights Reserved.</p>
        </div>
        <div class="col-md-6 col-xs-12">
            <p class="cookies-text">Informativa sulla privacy&ensp;|&ensp;Cookies&ensp;|&ensp;Gestione dei cookies</p>
        </div>
      </div>
    </div>
</footer>

templates/navbar.html
{% load tz %}

<nav class="navbar navbar-light" style="background-color: #ffffff; padding:10px 30px;">
    <div class="container-fluid d-flex justify-content-between align-items-end">
        <div class="d-flex align-items-end">
            <a class="navbar-brand" href="/">
                <img src="/static/images/tickez_logo.jpg" alt="tickez logo" width="110">
            </a>

            <div class="dropdown d-inline ms-4" style="margin-bottom: 7px;">
                <a style="color: black;" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Eventi
                </a>
                <ul class="dropdown-menu" style="min-width: max-content;">
                    <li><a class="dropdown-item" href="{% url 'products:events' %}?category=Concerti">Concerti</a></li>
                    <li><a class="dropdown-item" href="{% url 'products:events' %}?category=Festival">Festival</a></li>
                    <li><a class="dropdown-item" href="{% url 'products:events' %}?category=Teatro">Teatro</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'products:events' %}">Tutti gli eventi</a></li>
                </ul>
            </div>
        </div>

        <div>
            <form id="searchFormNavbar" class="d-flex w-100 ms-3 me-3" method="GET" action="{% url 'common:search-results' %}">
                <input class="form-control me-2" type="search" name="keywords" placeholder="Evento, Artista o Luogo" aria-label="Search" style="width: 320px;">
                <button class="btn btn-dark" type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>

        <div>
            {% if user.is_authenticated %}
            <div class="btn-group me-2">
                <button class="btn btn-dark rounded-end" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-bell position-relative" style="position: relative;">
                        {% if unread_count > 0 %}
                            <span class="notification-badge" style="position: absolute; top: -4px; right: -2px; width: 9px; height: 9px; background-color: red; border-radius: 50%;"></span>
                        {% endif %}
                    </i>
                </button>
                <ul class="dropdown-menu dropdown-menu-end">
                    {% for notification in notifications %}
                        <li>
                            <div class="d-flex justify-content-between align-items-center">
                                <a class="dropdown-item" href="{{ notification.evento.get_absolute_url }}" {% if not notification.letta %}style="font-weight: bold;"{% endif %}>
                                    {{ notification.testo }}
                                </a>
                                <span class="text-muted me-3" style="font-size: smaller; font-size: 11px; white-space: nowrap;">{{ notification.data_ora|timezone:"Europe/Rome"|date:"d/m/Y H:i" }}</span>
                            </div>
                        </li>
                    {% empty %}
                        <li class="dropdown-item">Nessuna notifica</li>
                    {% endfor %}
                </ul>
            </div>

            <a href={% if user.is_superuser %}"{% url 'users:admin-profile' %}"{% else %}"{% url 'users:profile' %}"{% endif %} class="btn btn-dark me-2">
                <span style="margin-right: 5px;">{{ user }}</span>
                <i class="fas fa-user-circle fa-lg"></i>
            </a>

            <form id="logout-form" method="POST" action="{% url 'users:logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-dark">
                    <i class="fas fa-sign-out-alt"></i>
                </button>
            </form>

            {% else %}

            <a href="{% url 'users:login' %}" class="btn btn-dark me-2">
                <span style="margin-right: 5px;">Accedi</span>
                <i class="fas fa-user-circle fa-lg"></i>
            </a>

            {% endif %}
        </div>
    </div>

    <!-- previene l'invio del form se il campo keywords è vuoto -->
    <script>
        document.getElementById("searchFormNavbar").addEventListener("submit", function(event) {
            var keywords = document.querySelector("#searchFormNavbar input[name='keywords']").value.trim();
            if (keywords === "") {
                event.preventDefault();
            }
        });
    </script>
</nav>