common/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'common'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.common, name=app_name),

    path('venues/', views.VenuesListView.as_view(), name="venues"),
    path('venues/<slug:slug>-<int:pk>/', views.VenueDetailView.as_view(), name="venue-details"),

    path('search/', views.search_results, name="search-results"),
]

orders/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'orders'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.orders, name=app_name),

    path('checkout/', views.checkout, name="checkout"),
    path('process-payment/', views.process_payment, name='process-payment'),

    path('edit-purchase/<slug:slug>-<int:pk>/', views.UpdatePurchaseView.as_view(), name="edit-purchase"),
]

products/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'products'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.products, name=app_name),

    path('events/', views.EventsListView.as_view(), name="events"),
    path('events/<slug:slug>-<int:pk>/', views.EventDetailView.as_view(), name="event-details"),

    path('create-event/', views.create_event, name="create-event"),
    path('update-event/<slug:slug>-<int:pk>/', views.UpdateEventView.as_view(), name="update-event"),
    path('delete-event/<slug:slug>-<int:pk>/', views.DeleteEventView.as_view(), name="delete-event"),

    path('create-ticket/<slug:event_slug>-<int:event_pk>/', views.create_ticket, name="create-ticket"),
    path('update-ticket/<slug:event_slug>-<int:event_pk>/<slug:ticket_slug>-<int:ticket_pk>/', views.UpdateTicketView.as_view(), name="update-ticket"),
    path('delete-ticket/<slug:event_slug>-<int:event_pk>/<slug:ticket_slug>-<int:ticket_pk>/', views.DeleteTicketView.as_view(), name="delete-ticket"),

    path('statistics/<slug:slug>-<int:pk>/', views.event_statistics, name="event-statistics"),
]

tickez/urls.py
from django.contrib import admin

from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
from django.views.generic.base import RedirectView


# definizione degli URL patterns per l'applicazione + aggiunta URL per servire file statici e media in fase di sviluppo
urlpatterns = [
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico', permanent=True)),
    re_path(r"^$|^\/$|^home\/$", views.home_page, name='homepage'),

    path('common/', include('common.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),

    re_path(r"^404/$", views.custom_404_view, name="404"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# personalizzazione dei titoli dell'area di amministrazione
admin.site.site_header = "Tickez Administration Page"
admin.site.site_title = "Tickez"
admin.site.index_title = "Admin Area"

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$", views.users, name=app_name),

    path('register/', views.CustomerCreateView.as_view(), name='register-customer'),
    path('register-organizer/', views.OrganizerCreateView.as_view(), name='register-organizer'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('admin-profile/', views.AdminProfileView.as_view(), name="admin-profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),

    path('toggle-follow/<str:entity_type>/<int:entity_pk>/', views.toggle_follow, name='toggle-follow'),

    path('artists/', views.ArtistsListView.as_view(), name="artists"),
    path('artists/<slug:slug>-<int:pk>/', views.ArtistDetailView.as_view(), name="artist-details"),
]

products/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.urls import reverse_lazy

from django.contrib import messages

from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin

from products.models import Evento, Biglietto
from users.models import Organizzatore
from common.models import Notifica
from orders.models import BigliettoAcquistato

from django.db.models import Count, Sum
from django.db.models.functions import TruncDay

from django.views.generic import ListView, DetailView, UpdateView, DeleteView

from .forms import *

from products.filters import EventoFilter

from datetime import datetime, timedelta
from django.utils import timezone

from django.conf import settings


def products(request):
    return render(request, '404.html', status=404)


# elenco eventi, filtrati ed in ordine temporale
class EventsListView(ListView):
    model = Evento
    template_name = 'products/events.html' 
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset().order_by('data_ora')
        self.evento_filter = EventoFilter(self.request.GET, queryset=queryset)
        return self.evento_filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.evento_filter
        return context

# dettagli evento
class EventDetailView(DetailView):
    model = Evento
    template_name = "products/event_details.html"

    def dispatch(self, request, *args, **kwargs):
        # gestisce eventuali eccezioni Http404 che potrebbero essere sollevate durante il processo di elaborazione della richiesta
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return render(request, '404.html', status=404)

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        pk = self.kwargs.get('pk')
        return get_object_or_404(Evento, slug=slug, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        evento = self.object

        evento.visualizzazioni += 1
        evento.save()

        # una notifica viene segnata come letta solo quando l'utente osserva i dettagli dell'evento in questione
        if self.request.user.is_authenticated:
            try:
                utente = self.request.user.utente
                notification = Notifica.objects.filter(evento=evento, organizzatore__in=utente.organizzatori_preferiti.all()).first()
                if notification and not notification.letta:
                    notification.letta = True
                    notification.save()
            except:
                utente = None

        context['title'] = f"{evento.organizzatore} - {evento.nome}"
        context['tickets'] = evento.biglietti_disponibili.all().order_by('-prezzo')
        context['range_dropdown'] = range(0, 6)
        context['name_change'] = evento.data_ora - timedelta(days=15)

        return context


# funzione di test per gestire l'autenticazione di admin ed organizzatori
def is_allowed(user):
    return user.is_superuser or user.groups.filter(name="Organizzatori").exists()

# mixin personalizzato per gestire l'autenticazione di admin ed organizzatori
class OrganizerOrSuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        obj = self.get_object()
        return user.is_superuser or (user.groups.filter(name="Organizzatori").exists() and obj.organizzatore.user == user)

    # se l'utente è autenticato ma non ha i permessi, solleva PermissionDenied
    def handle_no_permission(self):
        # in caso di tentato accesso ad una view protetta, senza i permessi adatti, reindirizza al login
        return redirect(f'{settings.LOGIN_URL}&next={self.request.path}')

# creazione notifica
def notify(event):
    organizzatore = event.organizzatore
    notification_text = f"Nuovo evento di {organizzatore.nome}: {event.nome} | Scopri i dettagli e Acquista!"

    Notifica.objects.create(
        testo=notification_text,
        data_ora=timezone.now(),
        organizzatore=organizzatore,
        luogo=event.luogo,
        evento=event
    )

@user_passes_test(is_allowed)
# creazione evento
def create_event(request):
    entity = 'Evento'
    form_class = AdminEventCrispyForm if request.user.is_superuser else EventCrispyForm

    if request.method == 'POST':
        form = form_class(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            event = form.save(commit=False)
            if request.user.is_superuser:
                # il form dell'admin prevede già un campo 'organizzatore'
                event.save()
                messages.success(request, f'Evento "{event.nome}" creato con successo!')
            else:
                try:
                    organizzatore = get_object_or_404(Organizzatore, user=request.user)
                    event.organizzatore = organizzatore
                    event.save()
                    messages.success(request, f'Evento "{event.nome}" creato con successo!')
                except Http404:
                    return render(request, '404.html', status=404)
            
            notify(event)
            return redirect(event.get_absolute_url())
    else:
        form = form_class(user=request.user)
    
    return render(request, 'products/create_entity.html', {'form': form, 'entity': entity})


@user_passes_test(is_allowed)
# creazione tipologia di biglietto
def create_ticket(request, event_slug, event_pk):
    entity = 'Biglietto'
    try:
        event = get_object_or_404(Evento, slug=event_slug, pk=event_pk)
    except Http404:
        return render(request, '404.html', status=404)

    if request.method == 'POST':
        form = TicketCrispyForm(request.POST, evento=event)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.evento = event
            ticket.organizzatore = event.organizzatore
            ticket.quantita_vendibile = ticket.quantita

            ticket.save()
            messages.success(request, f'Biglietto "{ticket.tipologia}" creato con successo!')
            return redirect(ticket.get_absolute_url())
    else:
        form = TicketCrispyForm()

    return render(request, 'products/create_entity.html', {'form': form, 'entity': entity, 'event': event})


# modifica evento
class UpdateEventView(OrganizerOrSuperuserRequiredMixin, UpdateView):
    model = Evento
    template_name = "products/update_entity.html"

    def dispatch(self, request, *args, **kwargs):
        # gestisce eventuali eccezioni Http404 che potrebbero essere sollevate durante il processo di elaborazione della richiesta
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return render(request, '404.html', status=404)

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        pk = self.kwargs.get('pk')
        return get_object_or_404(Evento, slug=slug, pk=pk)

    # sovrascrive get_form_class per determinare il form da utilizzare sulla base di self.request.user
    def get_form_class(self):
        return AdminEventCrispyForm if self.request.user.is_superuser else EventCrispyForm
    
    # il metodo form_valid è già implementato per gestire il salvataggio dell'istanza del modello
    def get_success_url(self):
        return self.object.get_absolute_url()
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['action'] = 'Salva Modifiche'
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Evento'
        context['name'] = self.object.nome
        return context
    
    def form_valid(self, form):
        messages.success(self.request, 'Modifiche salvate con successo!')
        return super().form_valid(form)
    

# modifica tipologia di biglietto associata ad un evento
class UpdateTicketView(OrganizerOrSuperuserRequiredMixin, UpdateView):
    model = Biglietto
    form_class = TicketCrispyForm
    template_name = "products/update_entity.html"
    slug_field = 'slug'

    def dispatch(self, request, *args, **kwargs):
        # gestisce eventuali eccezioni Http404 che potrebbero essere sollevate durante il processo di elaborazione della richiesta
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return render(request, '404.html', status=404)

    def get_object(self, queryset=None):
        self.event = get_object_or_404(Evento, slug=self.kwargs.get('event_slug'), pk=self.kwargs.get('event_pk'))
        queryset = self.event.biglietti_disponibili.filter(slug=self.kwargs.get('ticket_slug'))
        ticket = get_object_or_404(queryset, pk=self.kwargs.get('ticket_pk'))
        return ticket

    # il metodo form_valid è già implementato per gestire il salvataggio dell'istanza del modello
    def get_success_url(self):
        return self.event.get_absolute_url()
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['evento'] = self.event
        kwargs['action'] = 'Salva Modifiche'
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Biglietto'
        context['name'] = self.object.tipologia
        return context
    
    def form_valid(self, form):
        # aggiornamento e validazione di quantita_vendibile
        biglietti_acquistati = self.object.biglietti_acquistati.count()
        quantita = form.cleaned_data['quantita']
        self.object.quantita_vendibile = quantita - biglietti_acquistati

products/templates/products/base_products.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

products/templates/products/create_entity.html
{% extends "products/base_products.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}Crea {{entity}} | Tickez{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mb-5">Crea {{entity}}</h1>

    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        {% crispy form %}
    </form>
</div>
{% endblock %}

products/templates/products/create_event.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Crea Evento | Tickez{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST"> {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
{% endblock %}

products/templates/products/delete_entity.html
{% extends "products/base_products.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Elimina {{entity}} | Tickez{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mb-5">Elimina {{entity}}</h1>

    <form method="POST"> {% csrf_token %}
        <p>Sei sicuro di voler eliminare <strong>{{entity}}: {{name}}</strong>?</p>
        <input type="submit" value="Conferma" class="btn btn-danger">
    </form>
</div>
{% endblock %}

products/templates/products/delete_event.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Elimina Evento | Tickez{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST"> {% csrf_token %}
            <p><strong>{{ object.nome }}</strong> verrà eliminato. Sei sicuro?</p>
            <input type="submit" value="Conferma" class="btn btn-danger">
        </form>
    </div>
{% endblock %}

products/templates/products/event_details.html
{% extends "products/base_products.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}{{title}} | Tickez{% endblock %}

{% block content %}
<div class="container">
    <div class="d-flex flex-wrap align-items-center mb-5">
      <div class="me-3" style="width: 300px; height: 200px; flex-shrink: 0;">
          <img src="{{ object.locandina_url }}" style="width: 100%; height: 100%; object-fit: cover; border: 5px solid black;">
      </div>
  
      <div style="flex-grow: 1; max-width: calc(100% - 220px);">
          <h1 style="font-weight:600; word-break: break-word;">{{ object.nome }}</h1>
          <p><a href="{% url 'users:artist-details' object.organizzatore.slug object.organizzatore.pk %}" style="text-decoration: underline; color: black;">{{object.organizzatore}}</a><br>
             <a href="{% url 'common:venue-details' object.luogo.slug object.luogo.pk %}" style="text-decoration: underline; color: black;">{{object.luogo}}</a></p>
          <p>{{object.data_ora}}</p>
          
          {% if request.user.utente or request.user.is_superuser or not request.user.is_authenticated %}
          <form method="POST" action="{% url 'users:toggle-follow' entity_type='evento' entity_pk=object.id %}"> {% csrf_token %}
            <input type="hidden" name="action" value="{% if request.user.utente in object.followers.all %}unfollow{% else %}follow{% endif %}">
            <button type="submit" class="btn {% if request.user.utente in object.followers.all %}btn-secondary{% else %}btn-dark{% endif %}">
              {% if request.user.utente in object.followers.all %}
                <i class="fas fa-heart me-1"></i> Seguito
              {% else %}
                <i class="far fa-heart me-1"></i> Segui
              {% endif %}
            </button>
          </form>
          {% elif request.user.organizzatore and request.user.organizzatore == object.organizzatore %}
            <a href="{% url 'products:event-statistics' object.slug object.pk %}" class="btn btn-dark me-2"><i class="fa fa-line-chart" aria-hidden="true"></i></a>
            <a href="{% url 'products:update-event' object.slug object.pk %}" class="btn btn-dark me-2"><i class="fa-regular fa-pen-to-square" aria-hidden="true"></i></a>
            <a href="{% url 'products:delete-event' object.slug object.pk %}" class="btn btn-danger me-2"><i class="fa fa-trash" aria-hidden="true"></i></a>
          {% endif %}
      </div>
    </div>


    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="tickets-tab" data-bs-toggle="tab" data-bs-target="#tickets" type="button" role="tab" aria-controls="tickets" aria-selected="true">Biglietti</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" aria-selected="false">Descrizione</button>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="tickets" role="tabpanel" aria-labelledby="tickets-tab">
        {% if tickets %}
          <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
              <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </symbol>
          </svg>
          <div class="alert alert-warning d-flex align-items-center mt-3" role="alert" style="padding: 0.25rem 0.5rem; font-size: 0.8rem; border-radius: 0.25rem;">
            <svg class="bi flex-shrink-0 me-2" width="16" height="16" role="img" aria-label="Warning:"><use xlink:href="#info-fill"/></svg>
            <p style="margin: 0; flex-grow: 1;">Per questo evento sarà consentito eseguire la procedura di <u>cambio nominativo fino al {{ name_change|date:"d/m/Y" }}</u></p>
          </div>
        {% endif %}
        <form method="POST" action="{% url 'orders:checkout' %}"> {% csrf_token %}
          {% for t in tickets %}
            <div class="ticket-row d-flex justify-content-between align-items-center mb-3">
                <div class="col-md-8">
                    <strong class="{% if t.quantita_vendibile == 0 %}text-muted{% endif %}">{{ t.tipologia }}</strong>
                    <p class="{% if t.quantita_vendibile == 0 %}text-muted{% endif %}" style="overflow-wrap: break-word;">{{ t.descrizione }}</p>
                </div>
                <div class="col-md-4 d-flex justify-content-end">
                    {% if t.quantita_vendibile == 0 %}
                        <div class="d-flex align-items-center">
                            <span class="text-muted me-3">Non disponibile</span>
                            {% if request.user.organizzatore and request.user.organizzatore == object.organizzatore %}
                              <a href="{% url 'products:update-ticket' object.slug object.pk t.slug t.pk %}" class="btn btn-dark me-2">
                                  <i class="fa-regular fa-pen-to-square" aria-hidden="true"></i>
                              </a>
                              <a href="{% url 'products:delete-ticket' object.slug object.pk t.slug t.pk %}" class="btn btn-danger me-2">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                              </a>
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="d-flex align-items-center">
                          <span class="me-3">{{ t.prezzo }} €</span>
                          {% if request.user.organizzatore and request.user.organizzatore == object.organizzatore %}
                              <a href="{% url 'products:update-ticket' object.slug object.pk t.slug t.pk %}" class="btn btn-dark me-2">
                                  <i class="fa-regular fa-pen-to-square" aria-hidden="true"></i>
                              </a>
                              <a href="{% url 'products:delete-ticket' object.slug object.pk t.slug t.pk %}" class="btn btn-danger me-2">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                              </a>
                          {% else %}
                            {% if request.user.utente or request.user.is_superuser or not request.user.is_authenticated %}
                              <select class="form-select" name="quantita_{{ t.id }}" style="width: auto;">
                                  {% for i in range_dropdown %}
                                      <option value="{{ i }}">{{ i }}</option>
                                  {% endfor %}
                              </select>
                            {% endif %}
                          {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
          {% empty %}
            <p class="mt-3 text-muted">Nessun biglietto disponibile.</p>
          {% endfor %}
          {% if request.user.organizzatore and request.user.organizzatore == object.organizzatore  %}
              <div class="d-flex justify-content-center">
                  <a href="{% url 'products:create-ticket' object.slug object.pk %}" class="btn btn-dark">Aggiungi biglietto</a>
              </div>
          {% elif request.user.utente or request.user.is_superuser or not request.user.is_authenticated %}
            {% if tickets %}
              <div class="d-flex justify-content-center">
                <!-- input per recuperare la pagina dell'evento in caso non venga selezionato alcun biglietto -->
                <input type="hidden" name="evento_url" value="{{ object.get_absolute_url }}">
                <button type="submit" class="btn btn-dark">Compra</button>
              </div>
            {% endif %}
          {% endif %}
        </form>
      </div>
      <div class="tab-pane mt-3" id="description" role="tabpanel" aria-labelledby="description-tab">
        {{object.descrizione}}
      </div>
    </div>
</div>
{% endblock %}

products/templates/products/events.html
{% extends "products/base_products.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}Eventi | Tickez{% endblock %}

{% block content %}
<div class="container">
    <h1>Eventi</h1>
    <h5 class="mt-3 mb-5">Risultati: {{view.get_queryset.count}}</h5>

    <form id="filterForm" method="GET" class="mb-5">
        <div class="row">
            <div class="col-md-10 d-flex justify-content-start">
                <div class="form-group me-3">
                    {{ filter.form.category }}
                    {% if request.GET.category %}
                    <a  class="text-decoration-none text-dark ms-2" 
                        href="?{% for key, value in request.GET.items %}{% if key != 'category' %}{{ key }}={{ value }}{% if not forloop.last %}&{% endif %}{% endif %}{% endfor %}">
                        <i class="fas fa-times" style="font-size: 0.8rem;"></i>
                    </a>
                    {% endif %}
                </div>
                <div class="form-group me-3">
                    {{ filter.form.city }}
                    {% if request.GET.city %}
                    <a  class="text-decoration-none text-dark ms-2" 
                        href="?{% for key, value in request.GET.items %}{% if key != 'city' %}{{ key }}={{ value }}{% if not forloop.last %}&{% endif %}{% endif %}{% endfor %}">
                        <i class="fas fa-times" style="font-size: 0.8rem;"></i>
                    </a>
                    {% endif %}
                </div>
                <div class="form-group me-3">
                    {{ filter.form.from_date.label_tag }}
                    {{ filter.form.from_date }}
                </div>
                <div class="form-group">
                    {{ filter.form.until_date.label_tag }}
                    {{ filter.form.until_date }}
                    {% if request.GET.from_date or request.GET.until_date %}
                    <a  class="text-decoration-none text-dark ms-2" 
                        href="?{% for key, value in request.GET.items %}{% if key != 'from_date' and key != 'until_date' %}{{ key }}={{ value }}{% if not forloop.last %}&{% endif %}{% endif %}{% endfor %}">
                        <i class="fas fa-times" style="font-size: 0.8rem;"></i>
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-2 d-flex justify-content-end">
                <div class="form-group">
                    {{ filter.form.sort }}
                </div>
            </div>
        </div>
    </form>
    <!-- il form di filtraggio viene re-inviato ad ogni modifica dei filtri -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const form = document.getElementById('filterForm');
    
            form.addEventListener('change', function () {
                form.submit();
            });
        });
    </script>

    {% if page_obj %}
        {% for e in page_obj %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-4" style="max-width: 256px;">
                    <img src="{{ e.locandina_url }}" class="img-fluid rounded-start" alt="{{ e.nome }}" style="width: 256px; height:166px; object-fit: cover">
                </div>
                <div class="col-7">
                    <div class="card-body">
                        <h5 class="card-title mt-1 mb-2" style="font-weight:600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{ e.nome }}</h5>
                        <p></p>
                        <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{{e.organizzatore}}<br>{{ e.luogo}}</p>
                        <p class="card-text">{{e.data_ora|date:"d/m/Y, l"|slice:":15"}} {{e.data_ora|time:"H:i"}}</p>
                    </div>
                </div>
                <div class="card-body col-1 d-flex align-items-center justify-content-end">
                        <a href="{{ e.get_absolute_url }}" class="btn btn-dark">Biglietti <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p>Nessun evento disponibile.</p>
    {% endif %}

    <!-- paginazione -->
    <nav aria-label="Page navigation">
        <ul class="pagination pagination-sm justify-content-center">
            <li class="page-item">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            {% endif %}
            </li>
            
            <!-- link di paginazione per pagina corrente e adiacenti -->
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <li class="page-item">
                        <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{key}}={{value}}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item">
            {% if page_obj.has_next %}
                <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

products/templates/products/update_entity.html
{% extends "products/base_products.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}Modifica {{entity}} | Tickez{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mb-5">Modifica {{entity}}</h1>

    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        {% crispy form %}
    </form>
</div>
{% endblock %}

products/templates/products/update_event.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Modifica Evento | Tickez{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST"> {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
{% endblock %}